### ISSUE TITLE
Errors from latest version

### ISSUE THREAD

**Issue by cdhassell** [lesterchan/wp-useronline#14]
Following up from WP forums post today, I tried the version you linked from here.  It causes errors as follows:

[05-Jul-2018 11:07:35 UTC] PHP Warning:  include(/var/www/wordpress/wp-content/plugins/wp-useronline-master/scb/load.php): failed to open stream: No such file or directory in /var/www/wordpress/wp-content/plugins/wp-useronline-master/wp-useronline.php on line 14
[05-Jul-2018 11:07:35 UTC] PHP Warning:  include(): Failed opening '/var/www/wordpress/wp-content/plugins/wp-useronline-master/scb/load.php' for inclusion (include_path='/var/www/wordpress/wp-content/plugins/files/civicrm/extensions/braintree-master/com.paymentprocessor.braintree/:/var/www/wordpress/wp-content/plugins/files/civicrm/extensions/com.cividesk.email.sparkpost-1.1/:/var/www/wordpress/wp-content/plugins/woocommerce_civicrm-5b771fd0867312d154b02e263145dd84308f4da7/custom_tpl:/var/www/wordpress/wp-content/plugins/woocommerce_civicrm-5b771fd0867312d154b02e263145dd84308f4da7/custom_php:/var/www/wordpress/wp-content/plugins/files/civicrm/templates/:/var/www/wordpress/wp-content/plugins/files/civicrm/custom/code/:.:/var/www/wordpress/wp-content/plugins/civicrm/civicrm:/var/www/wordpress/wp-content/plugins/civicrm/civicrm/packages:/var/www/wordpress/wp-content/plugins/civicrm/civicrm/vendor/tecnickcom:/var/www/wordpress/wp-content/plugins/civicrm/civicrm/vendor/phpseclib/phpseclib/phpseclib:/var/www/wordpress/wp-content/plugins/civicrm/civicrm/ve in /var/www/wordpress/wp-content/plugins/wp-useronline-master/wp-useronline.php on line 14
[05-Jul-2018 11:07:35 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function scb_init() in /var/www/wordpress/wp-content/plugins/wp-useronline-master/wp-useronline.php:97
Stack trace:
#0 /var/www/wordpress/wp-admin/includes/plugin.php(555): include_once()
#1 /var/www/wordpress/wp-admin/plugins.php(43): activate_plugin('wp-useronline-m...', 'http://localhos...', false)
#2 {main}
  thrown in /var/www/wordpress/wp-content/plugins/wp-useronline-master/wp-useronline.php on line 97

**Comment by lesterchan** [comment]
OK, let me release 2.87.2. It shld solve this problem
